language: perl
perl:
  - "5.20"
  - "5.8"

env:
  global:
    - COVERAGE=1

before_install:
  - '[ $TRAVIS_PERL_VERSION = 5.8 ] && unset COVERAGE || :'
  - eval $(curl https://travis-perl.github.io/init) --auto
